#!/usr/bin/env node
/**
 * tokens-report.mjs
 * Generates reports/tokens-report.md — the allowed token vocabulary used by
 * design-contract and fe-implement.
 *
 * Reads tokens/primitives.json, tokens/semantics.json, tokens/typography.json
 * and writes a markdown report with every token name and its resolved value.
 */

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { resolve } from 'path';

const root = resolve(process.cwd());

function readJSON(path) {
  try {
    return JSON.parse(readFileSync(path, 'utf8'));
  } catch {
    return {};
  }
}

function flattenTokens(obj, prefix = '') {
  const leaves = [];
  for (const [key, val] of Object.entries(obj)) {
    if (key.startsWith('$')) continue;
    const path = prefix ? `${prefix}.${key}` : key;
    if (val && typeof val === 'object' && '$type' in val) {
      leaves.push({ path, type: val.$type, value: val.$value, layer: val.$extensions?.layer ?? 'unknown' });
    } else if (val && typeof val === 'object') {
      leaves.push(...flattenTokens(val, path));
    }
  }
  return leaves;
}

const primitives  = readJSON(resolve(root, 'tokens/primitives.json'));
const semantics   = readJSON(resolve(root, 'tokens/semantics.json'));
const typography  = readJSON(resolve(root, 'tokens/typography.json'));

const primLeaves = flattenTokens(primitives);
const semLeaves  = flattenTokens(semantics);
const typLeaves  = flattenTokens(typography).filter(t => t.type === 'typography');

const allLeaves = [...primLeaves, ...semLeaves, ...typLeaves];

// Count by type
const byType = {};
for (const t of allLeaves) {
  byType[t.type] = (byType[t.type] ?? 0) + 1;
}

// Group semantic tokens by category
const semByCategory = {};
for (const t of semLeaves) {
  const parts = t.path.split('.');
  const cat = parts.slice(0, 2).join('.');
  if (!semByCategory[cat]) semByCategory[cat] = [];
  semByCategory[cat].push(t.path);
}

// Check build artifacts
const cssExists = existsSync(resolve(root, 'tokens/build/tokens.css'));
const twExists  = existsSync(resolve(root, 'tokens/build/tailwind-tokens.js'));

// Shadow semantic tokens
const shadowTokens = semLeaves.filter(t => t.type === 'shadow').map(t => `\`${t.path}\``).join(' · ');

// Color surface tokens
const surfaceTokens = semLeaves.filter(t => t.path.startsWith('color.surface')).map(t => `\`${t.path}\``).join(' · ');
const textTokens    = semLeaves.filter(t => t.path.startsWith('color.text')).map(t => `\`${t.path}\``).join(' · ');
const borderTokens  = semLeaves.filter(t => t.path.startsWith('color.border')).map(t => `\`${t.path}\``).join(' · ');

// Spacing semantic tokens
const spaceTokens  = semLeaves.filter(t => t.path.startsWith('space.')).map(t => `\`${t.path}\``).join(' · ');
// Also spacing from primitives named "spacing.*"
const spacingPrims = primLeaves.filter(t => t.path.startsWith('spacing.')).map(t => `\`${t.path}\``).join(' · ');
// Radii
const radiiPrims   = primLeaves.filter(t => t.path.startsWith('radii.')).map(t => `\`${t.path}\``).join(' · ');
const radiusSem    = semLeaves.filter(t => t.path.startsWith('radius.')).map(t => `\`${t.path}\``).join(' · ');

const typCompounds = typLeaves.map(t => `\`${t.path}\``).join(' · ');

const now = new Date().toISOString().split('T')[0];

const report = `# tokens-report

Generated: ${now}
Generated by: \`npm run tokens:report\`

## Summary

| Metric | Count |
|--------|------:|
| Primitive leaves | ${primLeaves.length} |
| Semantic leaves | ${semLeaves.length} |
| Typography compounds | ${typLeaves.length} |
| **Total leaves** | ${allLeaves.length} |

### By \`$type\`

${Object.entries(byType).map(([t,c]) => `- \`${t}\`: ${c}`).join('\n')}

### By \`$extensions.layer\`

- \`primitive\`: ${allLeaves.filter(t => t.layer === 'primitive').length}
- \`semantic\`: ${allLeaves.filter(t => t.layer === 'semantic').length}

## Build artifacts

| File | Status |
|------|--------|
| \`tokens/build/tokens.css\` | ${cssExists ? 'present' : '**MISSING** — run npm run tokens:build'} |
| \`tokens/build/tailwind-tokens.js\` | ${twExists ? 'present' : '**MISSING** — run npm run tokens:build'} |

---

## Design-contract vocabulary

Use **semantic tokens** by default in app code, contracts, and Gherkin.
Fall back to primitives only when no semantic alias fits.

### Surface tokens (backgrounds)

${surfaceTokens}

### Text colour tokens

${textTokens}

### Border tokens

${borderTokens}

### Shadows

${shadowTokens}

### Spacing (semantic)

${spaceTokens || '_none — use primitives directly_'}

### Spacing (primitives — use when no semantic alias exists)

${spacingPrims}

### Radii (primitives)

${radiiPrims}

### Radii (semantic)

${radiusSem || '_none — use primitives directly_'}

### TYPOGRAPHY vocabulary (\`typography.json\`)

${typCompounds}

---

## All semantic tokens

${Object.entries(semByCategory).map(([cat, tokens]) => `### ${cat}\n\n${tokens.map(t => `\`${t}\``).join(' · ')}`).join('\n\n')}

---

## Token name reference

All tokens below are available in:
- CSS: \`var(--<token-path-with-hyphens>)\` e.g. \`var(--color-surface-card)\`
- Tailwind: via the token class utilities in \`tokens/build/tailwind-tokens.js\`

All token names must be used **exactly as listed** in contract.md and
implementation. Approximate substitutions (nearest-neighbour) are fidelity bugs.
`;

writeFileSync(resolve(root, 'reports/tokens-report.md'), report, 'utf8');
console.log('✓ reports/tokens-report.md written');
console.log(`  ${allLeaves.length} total tokens (${primLeaves.length} primitive + ${semLeaves.length} semantic + ${typLeaves.length} typography)`);
